- Content.Client/Chat/Managers/ChatManager.cs
- Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
- Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs
- Content.Server/Chat/Commands/SubtleCommand.cs
- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Shared/Chat/ChatChannel.cs
- Content.Shared/Chat/ChatSelectChannel.cs
- Content.Shared/Chat/SharedChatSystem.cs
- Content.Shared/_Coyote/ColorExtensions.cs
- Resources/Locale/en-US/Floof/chat/ui/chat-box.ftl
- Resources/Locale/en-US/chat/managers/chat-manager.ftl
- Resources/Prototypes/NPCs/debug.yml
https://github.com/ARF-SS13/coyotesector-14/pull/5
https://github.com/Floof-Station/Floof-Station/pull/14
**Changelog**
:cl: Superlagg
- add: subtles
- tweak: emotes dont go through walls and u got a color in ur name, lol
- fix: Fixed fun!
> Adds subtle and turbofucks speach

- Content.Server/Chat/Systems/ChatSystem.Emote.cs
- Content.Server/_Coyote/RoleplayIncentiveSystem.cs
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
> Robots get paid, no more double emotes

- Content.Shared/Preferences/HumanoidCharacterProfile.cs
- Resources/Prototypes/_EinsteinEngines/InventoryTemplates/ipc_inventory_template.yml
> Lets you put numbers and symbols and in your name

- Resources/Maps/_NF/Outpost/frontier.yml
> Add lib station to frontier.yml

- Resources/ServerInfo/Guidebook/NewPlayer/Controls/Roleplay.xml
> Adjusts roleplaying guidebook page

- Resources/Prototypes/Species/slime.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
- Resources/Prototypes/_EinsteinEngines/Species/ipc.yml
as opposed to just dying
**Changelog**
:cl:
- add: Slimes can be furries!
- tweak: IPCs just become a nightmare to play when their batteries die!
> Slimes get furry parts, IPCs become CBT when drained

- Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml
- Resources/Prototypes/_EinsteinEngines/Species/ipc.yml
- Resources/Prototypes/_NF/Species/goblin.yml
- Resources/Prototypes/_NF/Species/sheleg.yml
> Boob shirts and vulp screams

- Resources/Prototypes/_NF/PointsOfInterest/anomalousgeode.yml
see title
eschewing player interaction only ok if its a core need like food or water
> comments out anomalousgeode.yml

- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
:cl:
- add: You can talk and emote and such in crit!
> You can talk and emote and radio while in crit

- Resources/Prototypes/_NF/Entities/Structures/Specific/TradingCrates/crates.yml
Trade cargo crates, those things you buy from the trade mall and haul to cargo depots, shouldnt be a total loss anymore when you do it successfully. I watched a rat take one to the right station, and sell it for a 500$ loss. funch
> Crates are not a total loss anymore

- Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
This is partially to give a chance for two of for some of these jobs, so you can have a partner play them with you.
> Doubles up the Nash Station 1 of jobs

- Resources/Maps/_NF/Outpost/Nash.yml
Temp fix so players can get to their ships if they spawn on the sheriff dock, without admins needing to intervene.
**Changelog**
> Remove access restrictions to the sheriff dock

- Resources/Prototypes/_NF/PointsOfInterest/depots.yml
this lays the groundwork for future plans to expand the trading gameplay loop
> spaces cargo depots further from Nash

- Resources/Prototypes/_NF/Entities/Structures/Specific/TradingCrates/crates.yml
there's a lot of math involved with this, and a bit of "gutfeel" from experienced cargo players.
> FINALLY gets crates in line

- Resources/Maps/_NF/Outpost/Nash.yml
- Resources/Prototypes/Catalog/Cargo/cargo_atmospherics.yml
Fixes a infinite money glitch
Returns the crew monitoring server to Nash.
**Changelog**
> Fixes for gayme

- Resources/Locale/en-US/guidebook/guides.ftl
- Resources/Prototypes/Guidebook/lore.yml
- Resources/ServerInfo/Guidebook/Lore/LoreMaster.xml
- Resources/ServerInfo/Guidebook/Lore/Nanotrasen.xml
- Resources/ServerInfo/Guidebook/Lore/Solgov.xml
- Resources/ServerInfo/Guidebook/Lore/USSP.xml
- Resources/ServerInfo/Guidebook/NewPlayer/CharacterCreation.xml
Woe, lore upon yee.
**Changelog**
> The lore-enning.

- Resources/Prototypes/_NF/Loadouts/nfpirates_loadout_groups.yml
- Resources/Prototypes/_NF/Loadouts/role_loadouts.yml
Pirates can now pick most loadout items available to pilots, mercs, and contractors.
**Changelog**
> Expand pirates loadout options

- Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml
fixes rodentia chicks not being able to scream satifyingly enough
> lily can scream properly now

- Resources/Maps/_NF/Outpost/Nash.yml
Re-add ATM for the SR Office and Give the SR a Shuttle Records Console.
**Changelog**
> guys i found the obvious problems

- Content.Server/EntityEffects/EffectConditions/EventResponseCondition.cs
- Content.Server/EntityEffects/Effects/AdjustReagent.cs
- Content.Server/_Coyote/EventResponseReagentCondition/EventResponseReagentConditionComponent.cs
- Content.Server/_Coyote/EventResponseReagentCondition/EventResponseReagentConditionSystem.cs
- Content.Shared/EntityEffects/EntityEffect.cs
- Resources/Locale/en-US/_COYOTE/traits.ftl
- Resources/Prototypes/Reagents/toxins.yml
- Resources/Prototypes/_COYOTE/Traits.yml
- Resources/ServerInfo/Guidebook/Mobs/_DV/Felinid.xml
- Resources/ServerInfo/Guidebook/Mobs/_DV/Feroxi.xml
- Resources/ServerInfo/Guidebook/Mobs/_DV/Harpy.xml
- Resources/ServerInfo/Guidebook/Mobs/_DV/Rodentia.xml
- Resources/ServerInfo/Guidebook/Mobs/_DV/Vulpkanin.xml
And removes those things by default from all the species that had it before! Now you can choose to be a literal dog rat!
i hate this system (from a code perspective) why did I make it
> Adds Theobromine and Allicin intolerance traits

- Content.Client/UserInterface/Systems/Ghost/Controls/GhostTargetWindow.xaml.cs
- Content.Server/Ghost/GhostSystem.cs
Groups the dead and the ghosts and cryoed and such more neatly
> sorts the ghost stuff a bit better

- Resources/Prototypes/_NF/Entities/Objects/Books/hyperlinks.yml
Changes Space Law & NSFD SOP books, to point to our own hyperlinks, as opposed to Frontier's wiki.
**Changelog**
> Changes Space Law and NFSD SOP Book Hyperlinks

- Content.Server/_Coyote/CoolIncentives/CoolchefComponent.cs
- Content.Server/_Coyote/CoolIncentives/CoolchefSystem.cs
- Content.Server/_Coyote/RPIncentiveComponent.cs
- Content.Server/_Coyote/RoleplayIncentiveSystem.cs
- Resources/Prototypes/_COYOTE/Jobs/food_service.yml
- Resources/Prototypes/_NF/Roles/Jobs/Frontier/sr.yml
- Resources/Prototypes/_NF/Roles/Jobs/Frontier/stc.yml
- Resources/Prototypes/_NF/Roles/Jobs/Medical/doc.yml
- Resources/Prototypes/_NF/Roles/Jobs/Nfsd/sheriff.yml
- Resources/Prototypes/_NF/Roles/Jobs/Pirates/nfpirate.yml
- Resources/Prototypes/_NF/Roles/Jobs/Pirates/nfpirate_captain.yml
- Resources/Prototypes/_NF/Roles/Jobs/Pirates/nfpirate_first_mate.yml
Base RPI: 50 -> 80
New incentive modifiers:
Pirate: 1.45x
STC: 2.0x
SR: 2.5x
DOC: 2.0x
Sheriff: 2.0x
Modified incentive modifiers:
Servicer: 1.25x -> 1.5x
Broke Bitch Assistance
If you have below 100k bucks, you'll get more RPI pay.
Less than 100k: RPI is 100 (instead of 80)
Less then 75k: RPI is 200 (instead of 80)
Less then 40k: RPI is 300 (instead of 80)
Above 100k, RPI is 100k as normal
> Modifies Roleplay Incentive values

- Resources/Maps/_NF/Shuttles/Scrap/hotdog.yml
- Resources/Prototypes/_NF/Shipyard/Scrap/hotdog.yml
🌭 🚀 🐕 
Gods smallest scrapyard cargo vessel
> The FCY Hotdog

- Resources/Maps/_NF/Shuttles/Scrap/hotdog.yml
- Resources/Prototypes/_NF/Shipyard/Scrap/hotdog.yml
> Hotdog Fixes

- Resources/Prototypes/Interactions/noop_interactions.yml
now you wont hear people checkout other people
> Makes checkout only hearable by you

- Resources/Prototypes/_COYOTE/CoyoteBayouClothes/coyote_bayou_unififorms_items.yml
I learned regex because of this.
**Changelog**
> I'm attacking you with an axe

- Resources/Prototypes/_NF/PointsOfInterest/lpbravo.yml
we need more hope and love in the sector. 
we need less black and red IFFless edgelords ramming ships for giggles.
> commented out lpbravo.yml

- Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/expeditionaryflatpackvend.yml
forgot to do this last night
see title
> makes expedition flatpack vending machine iff computers infinite

- Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/box.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/food_base.yml
- Resources/Prototypes/Entities/Structures/Machines/smartfridge.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Mail/base_mail.yml
- Resources/Prototypes/_DV/Entities/Structures/Machines/smartfridge.yml
food should no longer rot in them.
> Adds a veg drawer to SMARTfridges

- Resources/Maps/_NF/Outpost/Nash.yml
- I ran the fixatmos thingy
- fixed some wires in main bathroom
- massage parlor
- shop area slightly adjusted
> Nash Touchup

- Content.Shared/Access/Components/IdCardComponent.cs
- Content.Shared/_NF/GridAccess/GridAccessComponent.cs
- Content.Shared/_NF/GridAccess/GridAccessSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
- Resources/Prototypes/Traits/speech.yml
- Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/ingredients.yml
- Resources/Prototypes/_NF/Entities/Structures/Machines/microwave_recipe_assemblers.yml
- Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml
Pulls some stuff from Frontier.
> Untap upkeep draw (8-13-25)

- Resources/Maps/_NF/Outpost/Nash.yml
> Fixes Nash dock & library power

- Resources/Maps/_NF/Outpost/Nash.yml
> Nash fixes - Smart Fridge & Some Lights

- Content.Server/Explosion/Components/TriggerOnMobstateChangeComponent.cs
- Content.Server/Explosion/EntitySystems/TriggerSystem.Mobstate.cs
- Content.Server/FloofStation/VoreSystem.cs
- Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
- Content.Shared/Mobs/MobState.cs
- Resources/Prototypes/_NF/Entities/Objects/Misc/subdermal_implants.yml
If vored, it'll block suit sensors, and block med implants from saying anything when they get messed up
also voring vgroid mobs wont drop their shit
> Enquietens Vore

- Content.Server/FloofStation/VoreSystem.cs
You no longer restore hunger by voring mobs. people really would rather eat uranium than go find food
> Fixes vore powergame

- Content.Shared/Weapons/Marker/SharedDamageMarkerSystem.cs
the crusher no longer heals off dead mobs. It also heals half as much if used against mobs that are in crit (mercs, syndeis, etc)
> Crusher balancing

- Content.Shared/CCVar/CCVars.Shuttle.cs
10080 minutes in heaven. have fun!
> Makes the rounds last a whole week

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
- Resources/Prototypes/Entities/Mobs/NPCs/hellspawn.yml
- Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
- Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/food_base.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
- Resources/Prototypes/_DV/Entities/Mobs/Species/feroxi.yml
- Resources/Prototypes/_DV/Entities/Mobs/Species/vulpkanin.yml
- Resources/Prototypes/_NF/Entities/Mobs/NPCs/baby_dragon.yml
- Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_argocyte.yml
> no more rot!

- Resources/Prototypes/_NF/PointsOfInterest/bahamamamas.yml
- Resources/Prototypes/_NF/PointsOfInterest/caseys.yml
- Resources/Prototypes/_NF/PointsOfInterest/courthouse.yml
- Resources/Prototypes/_NF/PointsOfInterest/edison.yml
- Resources/Prototypes/_NF/PointsOfInterest/lodge.yml
- Resources/Prototypes/_NF/PointsOfInterest/northpole.yml
- Resources/Prototypes/_NF/PointsOfInterest/thepit.yml
- Resources/Prototypes/_NF/PointsOfInterest/tinniasrest.yml
Adds back in most points of interest!
> Readds a bunch of PoIs

- Content.Server/StationEvents/Events/SolarFlareRule.cs
- Resources/Prototypes/_NF/Events/events.yml
Removes APC breaker event, suffocates people when that job is for my ass
Medical is unaffected by solar flares
> Event Stuff

- Content.Shared/CCVar/CCVars.Chat.cs
Ups the max post length to 10000
> hell yeah novelposting wooooo

- Content.Server/RoundEnd/RoundEndSystem.cs
Increases the shuttle call time to 1 hour
> hourlong shuttle call

- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml
- Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
IPCs are no longer immune to space, they take damage from low and high pressure environments
IPCs no longer have wierd thermoregulation issues, so they can actually wear coats and suits and whatever without literally dying from drip
Updated the IPC guide to actually list out more of the stuff you should know.
> Rebalances IPCs for a space based game

- Content.Server/_NF/CryoSleep/CryoSleepSystem.Returning.cs
- Content.Server/_NF/CryoSleep/CryoSleepSystem.cs
- Content.Shared/SSDIndicator/SSDIndicatorComponent.cs
- Content.Shared/SSDIndicator/SSDIndicatorSystem.cs
- Content.Shared/_Coyote/CryoBraindeadsComponent.cs
- Content.Shared/_NF/CryoSleep/CryoSleepComponent.cs
- Resources/Maps/_NF/Outpost/Nash.yml
- Resources/Maps/_NF/Outpost/frontier.yml
- Resources/Maps/_NF/Test/dev_map.yml
- Resources/Prototypes/_NF/Entities/Stations/nanotrasen.yml
- Resources/Prototypes/_NF/Maps/debug.yml
Yeah it does that, and yeah it lets them uncryo.
> Autocryos people who have been SSD in nash for more than 3 hours straight

- Resources/Prototypes/Damage/containers.yml
- Resources/Prototypes/Entities/Objects/Tools/welders.yml
> Silicons count as structural

- Content.Server/Power/EntitySystems/BatterySystem.cs
- Content.Server/_EinsteinEngines/Silicon/Charge/Systems/SiliconChargeSystem.cs
- Content.Shared/_EinsteinEngines/Silicon/Components/SiliconComponent.cs
- Resources/Prototypes/Damage/containers.yml
- Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
- Resources/Prototypes/Entities/Objects/Tools/welders.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml
- Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
oKAY it was an overcorrection, I'm sorry for trashing IPCs. Heres some changes
IPCs take structural damage, but at 50% the amount.
IPCs are immune to barotrauma!
However IPCs are not immune to the cold, and take extra cold damage too!
IPCs go into crit now, and it is the typical 100 crit, 200 dead.
IPCs take heat and blunt damage every few seconds while in crit.
Cable coils heal structural and cold too, and are generally much better for healing than before
> IPC addendums

- Content.Server/_Coyote/RPIncentiveComponent.cs
- Content.Server/_Coyote/RoleplayIncentiveSystem.cs
- Content.Server/_Coyote/RpiChatActionCategory.cs
- Content.Server/_Coyote/RpiChatRecord.cs
- Content.Shared/_Coyote/RolePlayIncentiveShared/GetRoleplayIncentiveModifier.cs
- Content.Shared/_Coyote/RolePlayIncentiveShared/RpiChatActionPrototype.cs
- Content.Shared/_Coyote/RolePlayIncentiveShared/RpiTaxBracketPrototype.cs
- Resources/Locale/en-US/_COYOTE/rp_incentive.ftl
- Resources/Prototypes/_COYOTE/RpiChatActions.yml
- Resources/Prototypes/_COYOTE/RpiTaxBrackets.yml
cleans it up a bit, nbd
also you lose a percentage of your cash if you die
> You suck and heres the bill

- Resources/Prototypes/Damage/containers.yml
> IPC no Structual

- Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/expeditionaryflatpackvend.yml
- Resources/Prototypes/_NF/Entities/Objects/Devices/flatpacks.yml
- Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
* svt no longer goes in pocket / svt no longer a small item / svt not a small item / svt not small item
* techfabs / techlathes in expeditionary flatpackvend / exped flatpackvend, increased price of R&D server
> jetbrains yaml practice v2

- Content.IntegrationTests/Tests/MaterialArbitrageTest.cs
- Resources/Prototypes/_COYOTE/Entities/Structures/Furniture/pole.yml
> INTEGS SUCK

- Resources/Prototypes/_COYOTE/Needs/NeedsDefault.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsDefaultNPC.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsRodentia.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsVulpkanin.yml
Makes it so people have to eat a lot less
> Nerfs hungerthirst

- Content.Server/Delivery/CargoDeliveryDataComponent.cs
- Content.Server/_DV/Mail/Components/MailComponent.cs
- Set minimum and maximum time to spawn mail to 30 minutes
- Set timer for mail to be considered trash to 360 minutes
**Changelog**
> Increased timers for Mail

- Content.Server/_Coyote/SpaceJanitor/SpaceJanitorSystem.cs
- Resources/Prototypes/Entities/Objects/Devices/flatpack.yml
- Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/flatpackvend.yml
also puts the R&D console in the flatpack vend
> kicks space janitor into overdrive

- Content.Client/Examine/ExamineSystem.cs
- Content.Server/_NF/CryoSleep/CryoSleepSystem.cs
- Content.Shared/SSDIndicator/SSDIndicatorSystem.cs
- Content.Shared/_Coyote/Needs/NeedDatum.cs
- Content.Shared/_Coyote/Needs/SharedNeedsSystem.cs
- Content.Shared/_NF/CCVar/NFCCVars.cs
- Resources/Prototypes/_COYOTE/Needs/NeedsAnimal.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsAnimalHuge.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsAnimalTiny.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsChiara.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsDefault.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsDefaultNPC.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsDragon.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsRat.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsRodentia.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsShark.yml
- Resources/Prototypes/_COYOTE/Needs/NeedsVulpkanin.yml
Makes the examine box less huge
Should remove the glitchy post-cryo do-after
Should make people not instantly cryo if they disconnect on Nash
Respawning is a lot faster
Being hungry isnt as speed-punishing
More aggressively checks if you're not awake, and if so, tries not to hungerfy you
> Hottie fixes

- Resources/Audio/MidiCustom/LICENSE.txt
Provide a default MIDI soundbank (GeneralUser-GS) for all MIDI music.
- Linux, Mac and Windows all had different default soundfonts, meaning music would sound different.
- The Windows default soundfont in particular has sucked since it was introduced with one of the pre-NT Windows, and nobody deserves to hear it in 2025 unless they're playing OG Doom.
- Also apparently Flatpack's default soundfont is bad too
- Also Windows was using a dls file which whilst supported by FluidSynth isn't supported by alternatives to FluidSynth and spews an error whenever it's loaded.
- This is the GeneralUser-GS soundfont bank, stripped of anything higher than 0-127. (The full bank has some synths and other music on other instruments, and might be worth mining for new instruments or options for the DAW).
- …
> Standardize and improve MIDI music with a good default soundfont from Upstream

- Content.Client/Shuttles/UI/NavScreen.xaml
- Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
- Content.Client/_NF/Shuttles/BUI/ShuttleConsoleBoundUserInterface.cs
- Content.Client/_NF/Shuttles/UI/NavScreen.xaml.cs
- Content.Client/_NF/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
- Content.IntegrationTests/Tests/EntityTest.cs
- Content.Server/DeviceLinking/Components/NoSignalOnLinkComponent.cs
- Content.Server/DeviceLinking/Systems/DeviceLinkSystem.cs
- Content.Server/Shuttles/Components/ShuttleConsoleComponent.cs
- Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
- Content.Server/_NF/Shuttles/Systems/ShuttleConsoleSystem.DeviceLinking.cs
- Content.Server/_NF/Shuttles/Systems/ShuttleConsoleSystem.OnConsoleStartup.cs
- Content.Server/_NF/Shuttles/Systems/ShuttleConsoleSystem.Startup.cs
- Content.Shared/Shuttles/Components/RadarConsoleComponent.cs
- Content.Shared/_NF/Shuttles/Events/ShuttlePortButtonPressedMessage.cs
- Resources/Locale/en-US/_NF/shuttles/console.ftl
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
- Resources/Prototypes/_COYOTE/Shuttles/device_linking_ports.yml
> shuttle console network ports

- Resources/Prototypes/Floof/Species/resomi.yml
- Resources/Prototypes/_DV/Species/rodentia.yml
- Resources/Prototypes/_NF/Species/goblin.yml
Increases the Resomi's smallest size. Now they're a lot closer to other races at smallest sizes.
> Further size tweaks

- Resources/Prototypes/_NF/Entities/Objects/Devices/plant_analyzer.yml
Changed plant analyzer scan delay from 10 seconds to 1 second.
A requested feature https://discord.com/channels/1387276222639378627/1421053712830300171/1421053712830300171
> Plant analyzer faster use

- Content.Client/Shuttles/UI/NavScreen.xaml
- Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
- Resources/Locale/en-US/_NF/shuttles/console.ftl
made the shuttle network ports prettier
partial port of https://github.com/Monolith-Station/Monolith/pull/1743/files to start learning xaml
> not a big fan of UI code

- Content.Client/UserInterface/Systems/Emotes/EmotesUIController.cs
- Content.Server/Chat/Systems/ChatSystem.Emote.cs
- Content.Server/Speech/EntitySystems/VocalSystem.cs
- Content.Shared/Speech/Components/VocalComponent.cs
- Resources/Prototypes/Voice/speech_emotes.yml
- Resources/Prototypes/_COYOTE/emotes_but_cooler.yml
- Resources/Prototypes/_COYOTE/speech_emote_sounds_but_cooler.yml
remove s the species lock on most emotes, makes certain species-specific variants able to be used... sort of
> Let the fuzzy fox sqeak and beep and honk and weh

- Resources/Maps/_NF/Outpost/Nash.yml
fixes nash pier 6 atmos
nashmos even
> fixes nash pier 6 atmos

- Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_hydroponics.yml
- Resources/Prototypes/_NF/Recipes/Lathes/Packs/biogen.yml
- Resources/Prototypes/_NF/Recipes/Lathes/biogen.yml
added the Pomegranate and Humpshroom seeds to the Biogen, added Pom, Hump, and Breedshroom seeds to the dungeon loot. 
**Changelog**
> New Seeds in Biogen and loot

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/Packs/clothing.yml
- Resources/Prototypes/Recipes/Lathes/clothing.yml
- Resources/Prototypes/Tiles/floors.yml
Added Socks and Thongs, along with Evening Wear and Collars, to the Uniform Printer
**Changelog**
> Printable Socks and Thongs, Evening Wear and Collars
